version: '3.8'
services:
 dynamodb-test:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-test
   ports:
     - "8000:8000"
   volumes:
     - "./dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal